### ISSUE TITLE
Generating the Whole Word together in a Single JPEG ??

### ISSUE THREAD

**Issue by ghanender-chauhan** [ghanender-chauhan/Text-to-handwritting-OSF#1]
In this programme the image of the given word is generating only two letters and the remaining letters is generating in another JPEG
Like - "WORLD" so its giving "WO" in one JPEG , "OR" in another JPEG , "RL" in another JPEG .
![Screenshot (5)](https://user-images.githubusercontent.com/72665196/103288915-f88cba00-4a0b-11eb-8f43-ad8bec7ad705.png)
![Screenshot (4)](https://user-images.githubusercontent.com/72665196/103288919-faef1400-4a0b-11eb-95cd-8660c03385ac.png)
![Screenshot (3)](https://user-images.githubusercontent.com/72665196/103288925-fdea0480-4a0b-11eb-9c71-5683f24d117b.png)

**Comment by av1shek** [comment]
I am interested to solve this issue please assign me

**Comment by ghanender-chauhan** [comment]
> I am interested to solve this issue please assign me


Just try to solve one issue at a time okay not all issue together

**Comment by av1shek** [comment]
Issue resolved, created a pull request and solved 3 issues so consider the points.
