### ISSUE TITLE
The Gap Between the letters 

### ISSUE THREAD

**Issue by ghanender-chauhan** [ghanender-chauhan/Text-to-handwritting-OSF#10]
**The gap is too for every successive letters try to decrease it **
![Screenshot (10)](https://user-images.githubusercontent.com/72665196/103472887-bc18df80-4db8-11eb-8526-23f2f01c2f80.png)

**Comment by Siddharth1006** [comment]
I would like to use pillow merge and see what i can do. Can u assign this issue to me?

**Comment by av1shek** [comment]
I would like to solve this issue Please please assign me , infact i have already solved i just have to create pull request, because I am working 2 and 3 issues and all these are inter related

**Comment by ghanender-chauhan** [comment]
> I would like to solve this issue Please please assign me , infact i have already solved i just have to create pull request, because I am working 2 and 3 issues and all these are inter related

@av1shek  you worked on many issues of mine ..... so give chance to other ones too

**Comment by av1shek** [comment]
@ghanender-chauhan Can I ask why PR is not merged I have submitted first no was assigned to this and I also did the same thing.

**Comment by saitejach127** [comment]
You should have first commented on it before starting working on it. Thats the rule. please do follow the rules

**Comment by av1shek** [comment]
> You should have first commented on it before starting working on it. Thats the rule. please do follow the rules

@saitejach127  I think you should see the above comments I already asked to assign this issue and also mentioned that It is almost complete and till then it was not assigned to any one.
And if you are talking about rules you should assign the issue before merging, we both asked but I solved first and submitted the PR and till then It was not assigned to any one.

So can you tell me why my PR is not merged ?

**Comment by saitejach127** [comment]
@av1shek The point is this. siddharth first commented on the issue to assign him then you commented. First come first serve is when he commented it's assigned to him. If you were already working on it you should have commented. So please follow the rules its for giving good exposure to real world open source because many people solving one issue is not efficient hence this system was made so that others dont work on it while you are working.

**Comment by ghanender-chauhan** [comment]
> > You should have first commented on it before starting working on it. Thats the rule. please do follow the rules
> 
> @saitejach127 I think you should see the above comments I already asked to assign this issue and also mentioned that It is almost complete and till then it was not assigned to any one.
> And if you are talking about rules you should assign the issue before merging, we both asked but I solved first and submitted the PR and till then It was not assigned to any one.
> 
> So can you tell me why my PR is not merged ?

You see in above comments i replied you ..."That give chance to other people also" If he will not able to do that work I will assign you ...and also siddhart commented first okay 
This is OSF Everyone comes here to learn so its my duty to give everyone a good opportunity to work on a issue you already worked on many issues on a single time and siddhart is taking the issue for the first time in my repository thats why i assigned him . If he will not be able do that then I will going to assign you the issue. So be Relax Its a Open Source fest , Everyone comes here to learn something new .... I just want everyone to participate in OSF . So @av1shek  give chance to everyone. 
Hope It will help you to clear your mind.
