### ISSUE TITLE
Autoname the save file ?

### ISSUE THREAD

**Issue by ghanender-chauhan** [ghanender-chauhan/Text-to-handwritting-OSF#2]
**We have to change the name of save file everytime before running the programme. It dosnt generating random names to save the file**

![Screenshot (6)](https://user-images.githubusercontent.com/72665196/103289263-c3349c00-4a0c-11eb-95fa-9795b033d736.png)

**Comment by Siddharth1006** [comment]
Can we use rename function (from the os module) and iteratively save the file names?

**Comment by ghanender-chauhan** [comment]
> Can we use rename function (from the os module) and iteratively save the file names?

Yep you can use...try it !!

**Comment by av1shek** [comment]
Can you explain more? What should be the name of file, is it dynamic different every time ?? if yes then what should be the naming criteria ?

**Comment by ghanender-chauhan** [comment]
> Can you explain more? What should be the name of file, is it dynamic different every time ?? if yes then what should be the naming criteria ?

You can randomly name the save file(and it should be different everytime)  make a function or anything you want....
