### ISSUE TITLE
How can we move to the next line after completing the sentence ? 

### ISSUE THREAD

**Issue by ghanender-chauhan** [ghanender-chauhan/Text-to-handwritting-OSF#3]
**If we complete a sentence by merging the successive images then, what should we do when we have to go for a next line . how to merge them ?? How to make a paragraph by using this programme**

**Comment by av1shek** [comment]
I would like to solve this issue, please assign me

**Comment by ghanender-chauhan** [comment]
> I would like to solve this issue, please assign me

Please complete the assigned issue...
